#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMVCDemo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbDEMO")]
	public partial class dbDemoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    partial void Insertftest(ftest instance);
    partial void Updateftest(ftest instance);
    partial void Deleteftest(ftest instance);
    #endregion
		
		public dbDemoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["dbDEMOConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbDemoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDemoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDemoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDemoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ftest> ftest
		{
			get
			{
				return this.GetTable<ftest>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ftest")]
	public partial class ftest : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _fid;
		
		private string _fName;
		
		private string _fPhone;
		
		private string _fEmail;
		
		private string _fAddress;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfidChanging(int value);
    partial void OnfidChanged();
    partial void OnfNameChanging(string value);
    partial void OnfNameChanged();
    partial void OnfPhoneChanging(string value);
    partial void OnfPhoneChanged();
    partial void OnfEmailChanging(string value);
    partial void OnfEmailChanged();
    partial void OnfAddressChanging(string value);
    partial void OnfAddressChanged();
    #endregion
		
		public ftest()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int fid
		{
			get
			{
				return this._fid;
			}
			set
			{
				if ((this._fid != value))
				{
					this.OnfidChanging(value);
					this.SendPropertyChanging();
					this._fid = value;
					this.SendPropertyChanged("fid");
					this.OnfidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fName", DbType="NVarChar(50)")]
		public string fName
		{
			get
			{
				return this._fName;
			}
			set
			{
				if ((this._fName != value))
				{
					this.OnfNameChanging(value);
					this.SendPropertyChanging();
					this._fName = value;
					this.SendPropertyChanged("fName");
					this.OnfNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fPhone", DbType="NVarChar(50)")]
		public string fPhone
		{
			get
			{
				return this._fPhone;
			}
			set
			{
				if ((this._fPhone != value))
				{
					this.OnfPhoneChanging(value);
					this.SendPropertyChanging();
					this._fPhone = value;
					this.SendPropertyChanged("fPhone");
					this.OnfPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fEmail", DbType="NVarChar(50)")]
		public string fEmail
		{
			get
			{
				return this._fEmail;
			}
			set
			{
				if ((this._fEmail != value))
				{
					this.OnfEmailChanging(value);
					this.SendPropertyChanging();
					this._fEmail = value;
					this.SendPropertyChanged("fEmail");
					this.OnfEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fAddress", DbType="NVarChar(50)")]
		public string fAddress
		{
			get
			{
				return this._fAddress;
			}
			set
			{
				if ((this._fAddress != value))
				{
					this.OnfAddressChanging(value);
					this.SendPropertyChanging();
					this._fAddress = value;
					this.SendPropertyChanged("fAddress");
					this.OnfAddressChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
